Tag color, refactor, bug fix, entry edit preliminary work

diff --git a/jrnl2 b/jrnl2
--- a/jrnl2
+++ b/jrnl2
@@ -1,18 +1,27 @@
 #!/usr/bin/env bash
 
+CFG_FILE="~/.jrnl2.rc"
 # parent tag included for all time-tracking entries
 TIME_TRACK_TAG="@time-track" 
 # If non-blank, use this journal for all time-tracking, instead of the default
 TIME_TRACK_JOURNAL=""
 MAIN_JOURNAL="$HOME/journals/journal.txt"
+TAG_COLOR="00;36" 
+
+#GREP_COLORS="mt=00;34" grep --color=always 'two\|$'
+#GREP_COLORS="mt=00;34" grep --color=always -e '' -e 'two'
 
 # If exists, reads the above configuration from the external config
-[ -f ~/.jrnl_helpers.rc ] && . ~/.jrnl_helpers.rc
+[[ -f "$CFG_FILE" ]] && . "$CFG_FILE"
 
 COMMANDS=()
 OPTIONS=()
 declare -A ARGS=()
 SEARCH_ARGS=()
+
+# TODO journal edit and delete operations (within search range)
+# TODO entry with custom date
+# TODO entry/search in custom journal
 
 function jrnl_time_start
 {
@@ -76,27 +85,55 @@ function jrnl_entry_import
 # TODO: date search (on, before, after, last week, last 7 days, ...)
     # Resolve partially via plain regex search on the date fields 
         # ie '^2018-(0[7-9]|10)' for July-October of 2018
+# TODO: for edit, save the first lines of searched/edited entries
+    # Once editing session complete, iterate through all entries:
+        # replace original entry with the edited, or with blank if absent in editing session
 function jrnl_entry_search
 {
-    n=0
+    max_entries=0
     [[ "${OPTIONS[*]}" =~ short ]] && instr='P' || instr='p'
-    [[ "${OPTIONS[*]}" =~ max_entries ]] && n=${ARGS['max_entries']}
-    # TODO: handle last line of file
-    search_cmd='sed -nr "/^[0-9]{4}-[0-9]{2}-[0-9]{2}/{x;//$instr;d}; {H;d}"'
+    [[ "${OPTIONS[*]}" =~ max_entries ]] && max_entries=${ARGS['max_entries']}
+    [[ "${OPTIONS[*]}" =~ edit ]] && edit=1
+    record_start_pat='^[0-9]{4}-[0-9]{2}-[0-9]{2}'
+    # case-insensitive match
+    # TODO: The last-line entry fails to match if it's a one-liner. Could place a blank line at end always.
+    search_cmd='sed -nr "/'$record_start_pat'/{x;/./I$instr;d}; \${x;G;/./I$instr}; {H}"'
     while [[ -n $1 ]]; do
         pattern=$1
-        search_cmd=$(sed -r 's/(\$instr)/{\/'"$pattern"'\/\1}/' <<< "$search_cmd")
+        search_cmd=$(sed -r 's/([^\/]*\$instr)/{\/'"$pattern"'\/\1}/g' <<< "$search_cmd")
         shift
     done
-    if [[ $n -gt 0 ]]; then
+    [[ -n $TAG_COLOR ]] && search_cmd_suf=" |GREP_COLORS='mt=$TAG_COLOR' grep --color -e '' -e '@\w\+'"
+    if [[ -n "$edit" ]]; then
+        tmpfile=$(mktemp --tmpdir jrnl-edit.XXXXXX)
+        trap 'rm "$tmpfile"' 0 1 15
+        search_cmd_suf=" > $tmpfile"
+    fi
+    if [[ $max_entries -gt 0 ]]; then
         prev_instr=$instr
         instr='P'
-        start_line=$(eval "$search_cmd $MAIN_JOURNAL | tail -$n | head -1")
+        # Use the start line, forward shell escaped, verbatim as the start search space
+        start_line=$(eval "$search_cmd $MAIN_JOURNAL | tail -$max_entries | head -1" | sed 's/\//\\\//g')
         instr=$prev_instr
-        sed -n "/$start_line/,\$p" "$MAIN_JOURNAL" | eval "$search_cmd" 
+        sed -n "/$start_line/,\$p" "$MAIN_JOURNAL" | eval "$search_cmd $search_cmd_suf" 
     else
-        eval "$search_cmd $MAIN_JOURNAL"
+        eval "$search_cmd $MAIN_JOURNAL $search_cmd_suf"
     fi
+#   if [[ -n "$edit" ]]; then
+#       entry_headers=$(sed "$record_start_pat" $tmpfile)
+#       $EDITOR $tmpfile
+#       num_edited=0
+#       num_deleted=0
+#       while read -r line; do
+#           grep -qF "$line" $tmpfile && (( num_edited++ )) || (( num_deleted++ ))
+#           new_record=$(sed -nr "/$record_start_pat/{x;/$line/{p;d;q}; {H;d}" $tmpfile)
+##           search_cmd='sed -nr "/'$record_start_pat'/{x;//$instr;d}; {H;d}"'
+#           #sed -ir "/$line/,/$record_start_pat/{H;{x;/$line/{d;" $MAIN_JOURNAL
+#       done <<< "$entry_headers"
+#       #edited=$(cat $tmpfile)
+#       [[ $num_edited -gt 0 ]] && echo "edited $num_edited entries"
+#       [[ $num_deleted -gt 0 ]] && echo "deleted $num_deleted entries"
+#   fi
 }
 
 # Adds entry in preference of
@@ -116,8 +153,7 @@ function jrnl_entry_add
             entry="${@:1}"
         else
             # TODO: how to wait for $EDITOR to truly exit?
-            # TODO: disregard empty file
-            tmpfile=$(mktemp --tmpdir jrnl-edit.XXXXXX)
+            tmpfile=$(mktemp --tmpdir jrnl-new.XXXXXX)
             trap 'rm "$tmpfile"' 0 1 15
             $EDITOR $tmpfile
             entry=$(cat $tmpfile)
@@ -136,40 +172,39 @@ function jrnl_entry_add
 #
 ## The stdout isn't immediately visible with each selected <ctrl>+<enter> tag as the entire output is piped to echo
 #alias jrnl_select_tags="jrnl --tags | awk '{print \$1}' | dmenu | xargs echo"
-#
-#alias jrnl_today_edit="jrnl -on today --edit"
-#alias jrnl_list_todos="jrnl @todo --short"
-#alias jrnl_list_daily="jrnl -and @daily @todo"
 
 function usage {
   cat <<EOF  
 Need to provide a command or alias.
-        -h|--help: help text,
-        -n|--max entries <n>: limit query to the last n entries,
-        -s|--search <pattern>: search for records containing <pattern>,
-        -t|--tags: view list of tags
-        --short: view entry headings only
-        --time_start: start timetracking a task
-        --time_end: stop timetracking
-        --time_report: report on all timetracking
+    -h|--help: help text,
+    -n|--max entries <n>: limit query to the last n entries,
+    -s|--search <pattern>: search for records containing <pattern>,
+    -e|--edit: edit the searched entries
+    -t|--tags: view list of tags
+    --short: view entry headings only
+    --time_start: start timetracking a task
+    --time_end: stop timetracking
+    --time_report: report on all timetracking
 EOF
 }
 
 function parseargs() {
     while [[ -n $1 ]]; do
-        args_needed=0
+        args_needed=false
+        is_opt=false
         case $1 in
             # Switches and configuration
             -t|--tags) COMMANDS+=('tags');;
             --short) OPTIONS+=('short');;
             -s|--search) 
-                args_needed=1
-                is_opt=0
+                args_needed=true
+                is_opt=false
                 cmd="search"
                 ;;
+            -e|--edit) OPTIONS+=('edit');;
             -n|--max_entries) 
-                args_needed=1
-                is_opt=1
+                args_needed=true
+                is_opt=true
                 cmd="max_entries"
                 ;;
             --time_start) COMMANDS+=("time_start");;
@@ -179,9 +214,9 @@ function parseargs() {
             *) return;; 
         esac
         shift
-        if [[ $args_needed == 1 ]]; then
+        if $args_needed; then
             [[ $# -lt 1 || $1 =~ ^\- ]] && echo "$cmd needs an argument" && exit 128
-            [[ $is_opt == 1 ]] && OPTIONS+=("$cmd") || COMMANDS+=("$cmd")
+            $is_opt && OPTIONS+=("$cmd") || COMMANDS+=("$cmd")
             [[ "$cmd" == "search" ]] && SEARCH_ARGS+=("$1") || ARGS["$cmd"]="$1" 
             shift
         fi
@@ -190,7 +225,11 @@ function parseargs() {
 
 parseargs "$@"
 
-[[ ${#COMMANDS} == 0 ]] && jrnl_entry_add "$@" && exit 0
+if [[ ${#COMMANDS} == 0 ]]; then
+    # if restrictive options present, filter on the entire journal
+    [[ ${#OPTIONS} == 0 ]] && jrnl_entry_add "$@" || jrnl_entry_search
+    exit 0
+fi
 
 case ${COMMANDS[0]} in
     search) jrnl_entry_search  "${SEARCH_ARGS[@]}";;
